services:
  mysql:
    image: 'mysql:latest'
    ports:
      - '3308:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=12345678'
      - 'MYSQL_DATABASE=playground'
      - 'MYSQL_USER=kalo'
      - 'MYSQL_PASSWORD=12345678'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
